### ISSUE TITLE
Có demo không bác ơi?

### ISSUE THREAD

**Issue by vfic** [toanmv-1729/wfms#62]
Có hình ảnh hay demo không bác? cách cài đặt như nào nhỉ?

**Comment by toanmv-1729** [comment]
demo mình có đẩy lên kobzaa.com nhé
bạn muốn thì gửi mình email mình tạo tài khoản cho bạn vào test nhé

**Comment by vfic** [comment]
dungnv@vfic.vn | Bác cho e xin tài khoản demo nhé. Cảm ơn bác.

**Comment by toanmv-1729** [comment]
bạn check email account với password nhé, mình để bạn quyền member nên 1 số chức năng thêm sửa xóa sẽ không sử dụng được

**Comment by vfic** [comment]
ok, cảm ơn bác
